AllCops:
  Include:
    - Gemfile
    - Rakefile

DotPosition:
  Enabled: false
EachWithObject:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
SignalException:
  Enabled: false
StringLiterals:
  Enabled: false
TrailingComma:
  Enabled: false
